---

#
# Tasks related to setting up matrix-synapse-rest-auth
#

- name: Fail if REST Auth enabled, but endpoint not configured
  fail:
    msg: "You have enabled the REST Auth password provider, but have not configured its endpoint in the `ext_password_provider_rest_auth_endpoint` variable. Consult the documentation."
  when: "ext_password_provider_rest_auth_enabled and ext_password_provider_rest_auth_endpoint == ''"

- name: Download matrix-synapse-rest-auth
  get_url:
    url: "{{ ext_password_provider_rest_auth_download_url }}"
    dest: "{{ synapse_ext_path }}/rest_auth_provider.py"
    force: true
    mode: 0555
  when: "ext_password_provider_rest_auth_enabled"

- set_fact:
    synapse_password_providers_enabled: true
  when: "ext_password_provider_rest_auth_enabled"

- set_fact:
    synapse_additional_loggers: >
      {{ synapse_additional_loggers }}
      +
      {{ [{'name': 'rest_auth_provider', 'level': 'INFO'}] }}
  when: "ext_password_provider_rest_auth_enabled"

#
# Tasks related to getting rid of matrix-synapse-rest-auth (if it was previously enabled)
#

- name: "Ensure matrix-synapse-rest-auth doesn't exist"
  file:
    path: "{{ synapse_ext_path }}/rest_auth_provider.py"
    state: absent
  when: "not ext_password_provider_rest_auth_enabled"



