---

#
# Tasks related to setting up matrix-synapse-shared-secret-auth
#

- name: Fail if Shared Secret Auth enabled, but no secret set
  fail:
    msg: "Shared Secret Auth is enabled, but no secret has been set in ext_password_provider_shared_secret_auth_shared_secret"
  when: "ext_password_provider_shared_secret_auth_enabled and ext_password_provider_shared_secret_auth_shared_secret == ''"

- name: Download matrix-synapse-shared-secret-auth
  get_url:
    url: "{{ ext_password_provider_shared_secret_auth_download_url }}"
    dest: "{{ synapse_ext_path }}/shared_secret_authenticator.py"
    force: true
    mode: 0555
  when: "ext_password_provider_shared_secret_auth_enabled"

- set_fact:
    synapse_password_providers_enabled: true
  when: "ext_password_provider_shared_secret_auth_enabled"

- set_fact:
    synapse_additional_loggers: >
      {{ synapse_additional_loggers }}
      +
      {{ [{'name': 'shared_secret_authenticator', 'level': 'INFO'}] }}
  when: "ext_password_provider_shared_secret_auth_enabled"

#
# Tasks related to getting rid of matrix-synapse-shared-secret-auth (if it was previously enabled)
#

- name: "Ensure matrix-synapse-shared-secret-auth doesn't exist"
  file:
    path: "{{ synapse_ext_path }}/shared_secret_authenticator.py"
    state: absent
  when: "not ext_password_provider_shared_secret_auth_enabled"

