---

- set_fact:
    synapse_password_providers_enabled: true
  when: "ext_password_provider_ldap_enabled"

- set_fact:
    synapse_additional_loggers: >
      {{ synapse_additional_loggers }}
      +
      {{ [{'name': 'ldap_auth_provider', 'level': 'INFO'}] }}
  when: "ext_password_provider_ldap_enabled"
