---

- name: "coturn / get public IP"
  ipify_facts:
  when: turn_external_ip_address == ""

- name: "coturn / set public IP"
  set_fact:
    turn_external_ip_address: "{{ ipify_public_ip }}"
  when: turn_external_ip_address == ""


- name: "coturn / install packages"
  apt:
    state: present
    name:
      - coturn

- name: "coturn / configure the server"
  blockinfile:
    dest: /etc/turnserver.conf
    insertafter: EOF
    block: |
      lt-cred-mech
      use-auth-secret
      static-auth-secret={{ turn_shared_secret }}
      realm={{ matrix_server_fqn_matrix }}
      cert=/etc/matrix-synapse/homeserver.tls.crt
      pkey=/etc/matrix-synapse/homeserver.tls.key
      dh-file=/etc/matrix-synapse/homeserver.tls.dh
      cipher-list="HIGH"
      min-port={{ turn_udp_min_port }}
      max-port={{ turn_udp_max_port }}
      external-ip={{ turn_external_ip_address }}
      log-file=/var/log/turn.log
      userdb=/var/lib/turnserver.db
      no-cli
      # blocking local, link-local and ubuntu fan networks
      denied-peer-ip=10.0.0.0-10.255.255.255
      denied-peer-ip=192.168.0.0-192.168.255.255
      denied-peer-ip=172.16.0.0-172.31.255.255
      denied-peer-ip=240.0.0.0-240.255.255.255
      denied-peer-ip=169.254.0.0-169.254.255.255

- name: "coturn / set /etc/default/coturn"
  lineinfile: dest=/etc/default/coturn
  args:
    line: "TURNSERVER_ENABLED=1"

- name: "coturn / ensure turn server is enabled and (re)started"
  service: name=coturn state=restarted enabled=yes
