---

- include: sanity-check.yml
- include: ma1sd.yml
  when: ma1sd_enabled == true
- include: riot-web.yml
- name: Ensure extension install path exists
  file:
    path: "{{ synapse_ext_path }}"
    state: directory
- include: synapse-install.yml
- import_tasks: "extensions/password-provider-rest-auth.yml"
- import_tasks: "extensions/password-provider-shared-secret-auth.yml"
- import_tasks: "extensions/appservice-mautrix-facebook.yml"
- import_tasks: "extensions/appservice-mautrix-whatsapp.yml"
- import_tasks: "bots/bot-maubot.yml"
- include: synapse-setup.yml
- include: coturn.yml

# Dimension support likely won't happen before dimension release 1.0
# npm dependency hell makes this package basically unmanagable.
#- include: dimension.yml
#  when: dimension_enabled == true


