---


#add dns selfcheck 
# - https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-base/tasks/self_check_dns.yml
# - includes: #https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-base/tasks/self_check_dns_srv.yml



# add chrony!

- include: sanity-check.yml
- include: mxisd.yml
  when: mxisd_enabled == true
#- include: riot-web.yml
- name: Ensure extension install path exists
  file:
    path: "{{ synapse_ext_path }}"
    state: directory
- include: synapse-pre.yml
- import_tasks: "extensions/password-provider-rest-auth.yml"
- import_tasks: "extensions/password-provider-shared-secret-auth.yml"
- import_tasks: "extensions/appservice-mautrix-whatsapp.yml"
- include: synapse.yml
- include: synapse-post.yml
- include: coturn.yml


# add svc https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/tasks/ext/mautrix-telegram/setup.yml
# add svc https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/tasks/ext/mautrix-whatsapp/setup.yml
# https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/roles/matrix-synapse/tasks/ext/shared-secret-auth
# https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/roles/matrix-synapse/tasks/ext/rest-auth