---

- name: Install matrix-mxisd dependencies
  apt:
    state: present
    update_cache: yes
    name: openjdk-8-jre-headless

- name: "Ensure /var/mxisd directory exists"
  file:
    path: /var/mxisd
    state: directory

- name: Install matrix-mxisd
  apt:
    deb: "https://github.com/kamax-matrix/mxisd/releases/download/v{{ mxisd_version }}/mxisd_{{ mxisd_version }}_all.deb"

- name: Ensure mxisd config installed
  copy:
    content: "{{ mxisd_configuration|to_nice_yaml }}"
    dest: "{{ mxisd_config_path }}/mxisd.yaml"
    mode: 0644

- name: Ensure mxisd server is restarted and enabled
  service: name=mxisd state=restarted enabled=yes

- set_fact:
    mxisd_url_endpoint_public: "https://{{ matrix_server_fqn_matrix }}/_matrix/identity/api/v1"

- name: Check mxisd Identity Service
  uri:
    url: "{{ mxisd_url_endpoint_public }}"
    follow_redirects: false
    validate_certs: true
  register: result_mxisd
  ignore_errors: true

- name: Fail if mxisd Identity Service not working
  fail:
    msg: "Failed checking mxisd is up at `{{ matrix_server_fqn_matrix }}` (checked endpoint: `{{ mxisd_url_endpoint_public }}`). Is mxisd running? Is port 443 open in your firewall? Full error: {{ result_mxisd }}"
  when: "result_mxisd.failed or 'json' not in result_mxisd"

- name: Report working mxisd Identity Service
  debug:
    msg: "mxisd at `{{ matrix_server_fqn_matrix }}` is working (checked endpoint: `{{ mxisd_url_endpoint_public }}`)"
