---

- name: "riot-web / add apt keys"
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://dl.yarnpkg.com/debian/pubkey.gpg"

- name: "riot-web / add apt repos"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://dl.yarnpkg.com/debian/ stable main"

- name: "riot-web / install dependencies"
  apt:
    state: latest
    update_cache: yes
    name:
      #- nodejs
      - yarn
      - nginx

- name: "riot-web / clone riot-web from Github"
  git: repo=https://github.com/vector-im/riot-web.git dest=/opt/riot-web version={{ riot_version }} force=yes

- name: "riot-web / npm install"
  shell: yarn install
  args:
    chdir: /opt/riot-web

- name: "riot-web / update config.json"
  template:
    src: "riot.config.j2"
    dest: "/opt/riot-web/config.json"

#- name: "riot-web / update config.{{ matrix_server_fqn_riot }}.json"
#  template:
#    src: "riot.config.j2"
#    dest: "/opt/riot-web/config.{{ matrix_server_fqn_riot }}.json"

- name: "riot-web / npm run dist"
  shell: yarn dist
  args:
    chdir: /opt/riot-web

- name: "riot-web / set nginx's client_max_body_size"
  lineinfile: dest=/etc/nginx/nginx.conf
  args:
    regexp: "^(.*)client_max_body_size(.*)"
    line: "	client_max_body_size {{ max_upload_size }}; # Ansible managed"
    insertafter: "^http {"
  notify:
    - restart nginx

- name: "riot-web / configure default nginx site to serve riot-web, restart nginx"
  template:
    src: nginx-default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: "riot-web / make sure nginx service is enabled"
  service: name=nginx enabled=yes state=restarted

- name: "riot-web / post-install check"
  uri:
    url: "https://{{ matrix_server_fqn_riot }}/config.json"
    follow_redirects: false
    validate_certs: yes
  register: result_riot_web
  ignore_errors: true

- name: "riot-web / post-install check / fail on errors"
  fail:
    msg: "Failed checking riot-web is up at `{{ matrix_server_fqn_riot }}` (checked endpoint: `https://{{ matrix_server_fqn_riot }}/config.json`). Is Riot running? Is port 443 open in your firewall? Are the SSL certs ok? Is the config.json a valid json? Full error: {{ result_riot_web }}"
  when: "result_riot_web.failed or 'json' not in result_riot_web"

- name: "Riot-web / post-install check / pass on working riot-web"
  debug:
    msg: "riot-web at `{{ matrix_server_fqn_riot }}` is working (checked endpoint: `https://{{ matrix_server_fqn_riot }}/config.json`)"

