---


- name: Fail if required settings not defined
  fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`) first.
  when: "vars[item] | length == 0"
  with_items:
    - "turn_shared_secret"
    - "synapse_macaroon_secret_key"

- name: Fail if uppercase domain used
  fail:
    msg: "Detected that you're using an uppercase domain name - `{{ item }}`. This will cause trouble. Please use all-lowercase!"
  when: "item != item|lower"
  with_items:
    - "{{ matrix_domain }}"
    - "{{ matrix_server_fqn_identity }}"
    - "{{ matrix_server_fqn_matrix }}"
    - "{{ matrix_server_fqn_riot }}"

- name: Fail if matrix_server_fqn_matrix and matrix_server_fqn_riot are the same
  fail:
    msg: "Running Riot and Synapse from the same domain is not recommended due to the risk of XSS vulnerabilities (see https://github.com/vector-im/riot-web/issues/1977)."
  when: "matrix_server_fqn_matrix == matrix_server_fqn_riot"


- name: Fail if required Dimension settings not defined
  fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using Dimension.
  with_items:
    - "dimension_access_token"
  when: "dimension_enabled and vars[item] == ''"

- name: Fail if Matrix Federation is disabled
  fail:
    msg: >-
      You need to enable Matrix Federation to use Dimension. Set `{{ item }}` to 'true'.
  with_items:
    - "disable_federation"
  when: "dimension_enabled|bool and disable_federation|bool"

- name: Fail if synapse registration requires a msisdn 3PID, when msisdn is disabled at the same time
  fail: msg="Resolve conflict between synapse_registrations_require_3pid and synapse_disable_msisdn_registration"
  when: synapse_disable_msisdn_registration and 'msisdn' in synapse_registrations_require_3pid

# add chrony!


# add svc https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/tasks/ext/mautrix-telegram/setup.yml
# add svc https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/tasks/ext/mautrix-whatsapp/setup.yml
# https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/roles/matrix-synapse/tasks/ext/shared-secret-auth
# https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/roles/matrix-synapse/tasks/ext/rest-auth