---

- name: Fail if required Synapse settings not defined
  fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`) for using Synapse.
  when: "vars[item] == ''"
  with_items:
    - "synapse_macaroon_secret_key"


- name: Add matrix-synapse repo gpg key
  apt_key:
    url: "https://packages.matrix.org/debian/matrix-org-archive-keyring.asc"
    state: present

- name: Add matrix-synapse repo
  apt_repository:
    repo: "deb https://packages.matrix.org/debian/ {{ ansible_lsb.codename|lower }} main"

- name: Install packages needed by matrix-synapse
  apt:
    state: present
    update_cache: yes
    name:
     - matrix-synapse-py3  # matrix-synapse propper
     - sqlite3             # sqlite backend
     - postgresql          # postgres backend
     - postgresql-contrib  # postgres backend

- name: Install matrix-synapse-ldap if needed
  apt:
    state: present
    name: matrix-synapse-ldap3
  when: ext_password_provider_ldap_enabled

