---

- name: "Ensure /etc/matrix-synapse/conf.d/server_name.yaml is configured"
  lineinfile: dest=/etc/matrix-synapse/conf.d/server_name.yaml
  args:
    regexp: "^(.*)server_name:(.*)"
    line: "server_name: {{ matrix_domain }}"
    create: yes

- name: "Ensure /etc/matrix-synapse/conf.d/report_stats.yaml is configured"
  lineinfile: dest=/etc/matrix-synapse/conf.d/report_stats.yaml
  args:
    regexp: "^(.*)report_stats:(.*)"
    line: "report_stats: {{ synapse_report_stats }}"
    create: yes

- name: "Ensure /etc/matrix-synapse/homeserver.yaml is configured"
  template:
    src: synapse_homeserver.yaml.j2
    dest: /etc/matrix-synapse/homeserver.yaml

- name: Ensure Matrix log config installed
  template:
    src: "synapse_log.yaml.j2"
    dest: "/etc/matrix-synapse/log.yaml"

- name: Ensure templates and well-known dirs exist
  file: path="{{ item }}" state=directory
  with_items:
    - "/opt/synapse/.well-known/matrix"
    - "/opt/synapse/templates"

- name: "Ensure .well-known files are set in place"
  template:
    src: "well-known-{{ item }}.j2"
    dest: "/opt/synapse/.well-known/matrix/{{ item }}"
  with_items:
    - client
    - server

- name: Ensure matrix-synapse server is restarted and enabled
  service: name=matrix-synapse state=restarted enabled=yes

- name: Wait a while, so that Matrix Synapse can manage to start
  pause:
    seconds: 7

- name: Register users
  shell: "/usr/bin/register_new_matrix_user -u {{ item.user }} -p {{ item.pass }} -c /etc/matrix-synapse/homeserver.yaml {{ '--admin' if item.admin | default('--no-admin') }} 'http://localhost:8008'"
  with_items: "{{ matrix_users }}"
  ignore_errors: yes
  when: matrix_users and matrix_users | length > 0


# do defaultu
#matrix_synapse_id_servers_public: ['vector.im', 'matrix.org']

#matrix_synapse_macaroon_secret_key: ""
#matrix_synapse_registration_shared_secret: "{{ matrix_synapse_macaroon_secret_key }}"
#matrix_synapse_form_secret: "{{ matrix_synapse_macaroon_secret_key }}"
# test na vyplneny macaroon


# testy:
# do vars
#matrix_synapse_client_api_url_endpoint_public: "https://{{ hostname_matrix }}/_matrix/client/versions"
#matrix_synapse_federation_api_url_endpoint_public: "https://{{ hostname_matrix }}:8448/_matrix/federation/v1/version"
# do tasku
# https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/tasks/self_check_client_api.yml
# https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/tasks/self_check_federation_api.yml



# env-synapse
# SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
# SYNAPSE_CACHE_FACTOR={{ matrix_synapse_cache_factor }}


# zkoncil jsem zde
# https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-synapse/defaults/main.yml#L39