- name: start synapse
  service: name=synapse state=started

- name: restart synapse
  service: name=synapse state=restarted
  
- name: start coturn
  service: name=coturn state=started

- name: restart coturn
  service: name=coturn state=restarted

- name: restart nginx
  service: name=nginx state=restarted
