#- name: start synapse
#  service: name=synapse state=started

- name: restart matrix-synapse
  service: name=matrix-synapse state=restarted

- name: restart mautrix-whatsapp
  service: name=mautrix-whatsapp state=restarted

- name: start coturn
  service: name=coturn state=started

- name: restart coturn
  service: name=coturn state=restarted

- name: restart nginx
  service: name=nginx state=restarted
